Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,8 +25,18 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      # build & test
-      - run: docker build -t app .
+      # Build & Test Docker Image
+      - name: Build Docker image
+        run: docker build -t app .
+        
+      # Check if the build succeeded
+      - name: Check Build Status
+        if: ${{ success() }}
+        run: exit 0
+      # If the build failed, exit with a non-zero code
+      - name: Fail Build
+        run: exit 1
+      
       
       # Configure Git
       - name: Configure Git
