Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,48 +1,38 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      # Build & Test Docker Image
       - name: Build Docker image
-        run: docker build -t app .
-        
-      # Configure Git
+        run: |
+          docker build -t app .
+          # Ajoutez une vérification conditionnelle pour vérifier si la construction Docker a réussi
+          if [ $? -ne 0 ]; then
+            echo "Build Docker failed. Exiting."
+            exit 1
+          fi
+
       - name: Configure Git
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
       
-      # Authenticate with GitHub token
       - name: Authenticate with GitHub
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
       
-      # Create a Tag
       - name: Create Tag
         id: create_tag
         run: |
@@ -52,7 +42,6 @@ jobs:
           git tag $TAG_NAME
           git push origin $TAG_NAME
 
-      # Create a GitHub Release
       - name: Create Release
         uses: actions/create-release@v1
         env:
@@ -65,4 +54,3 @@ jobs:
             - Description of changes in this release
           draft: false
           prerelease: false
-      
